/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.mycompany.rogueapp.agencia;
import com.mycompany.rogueapp.users;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import javax.swing.BorderFactory;
import org.ektorp.CouchDbConnector;
import org.ektorp.CouchDbInstance;
import org.ektorp.impl.StdCouchDbConnector;
import views.*;

/**
 *
 * @author Gisselle Lagos
 */
public class createAgencies extends javax.swing.JPanel {
CouchDbInstance dbInstance;
    /**
     * Creates new form createAgencies
     * @param dbInstance
     */
    public createAgencies(CouchDbInstance dbInstance) {
       this.dbInstance=dbInstance;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_createAgencyEmail = new javax.swing.JTextField();
        tf_createAgencyRTN = new javax.swing.JTextField();
        tf_createAgencyPhone = new javax.swing.JTextField();
        tf_createAgencyDirector = new javax.swing.JTextField();
        tf_createAgencyName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_createAgencyDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_createAgencyAddress = new javax.swing.JTextArea();
        jb_createAgency = new javax.swing.JButton();
        jp_createAgencyPassword = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nueva agencia");

        tf_createAgencyDescription.setColumns(20);
        tf_createAgencyDescription.setRows(5);
        jScrollPane1.setViewportView(tf_createAgencyDescription);

        jLabel2.setText("Correo");

        jLabel3.setText("Password");

        jLabel4.setText("RTN");

        jLabel5.setText("Dirección");

        jLabel6.setText("Teléfono");

        jLabel7.setText("Director");

        jLabel8.setText("Nombre");

        jLabel9.setText("Descripción");

        tf_createAgencyAddress.setColumns(20);
        tf_createAgencyAddress.setRows(5);
        jScrollPane2.setViewportView(tf_createAgencyAddress);

        jb_createAgency.setText("Crear");
        jb_createAgency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_createAgencyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jb_createAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_createAgencyEmail)
                                    .addComponent(tf_createAgencyRTN)
                                    .addComponent(tf_createAgencyName)
                                    .addComponent(jp_createAgencyPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel5)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_createAgencyDirector)
                                            .addComponent(tf_createAgencyPhone)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_createAgencyPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(tf_createAgencyDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_createAgencyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jp_createAgencyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_createAgencyRTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tf_createAgencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jb_createAgency, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_createAgencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_createAgencyMouseClicked
        boolean error = false;

        if (tf_createAgencyEmail.getText().equals("")) {
            tf_createAgencyEmail.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (jp_createAgencyPassword.getText().equals("")) {
            jp_createAgencyPassword.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (tf_createAgencyRTN.getText().equals("")) {
            tf_createAgencyRTN.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (tf_createAgencyName.getText().equals("")) {
            tf_createAgencyName.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (tf_createAgencyPhone.getText().equals("")) {
            tf_createAgencyPhone.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (tf_createAgencyDirector.getText().equals("")) {
            tf_createAgencyDirector.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (tf_createAgencyAddress.getText().equals("")) {
            tf_createAgencyAddress.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (tf_createAgencyDescription.getText().equals("")) {
            tf_createAgencyDescription.setBorder(BorderFactory.createLineBorder(Color.red));
            error = true;
        }
        if (!error) {

            System.out.println("DB insert");
            String username = tf_createAgencyEmail.getText();
            String password = jp_createAgencyPassword.getText();
            String RTN = tf_createAgencyRTN.getText();
            String nombre = tf_createAgencyName.getText();
            String direccion = tf_createAgencyDirector.getText();
            int telefono = parseInt(tf_createAgencyPhone.getText());
            String director = tf_createAgencyDirector.getText();
            String descripcion = tf_createAgencyDescription.getText();
            agencia newAgencia = new agencia(username, RTN, nombre, direccion, telefono, director, descripcion);
            users newUser = new users(username, password, "agencia");

            //--------------- Creating database----------------------------//
            CouchDbConnector dbAgencia = new StdCouchDbConnector("agencia",dbInstance);
            CouchDbConnector dbUsers = new StdCouchDbConnector("users", dbInstance);
            dbAgencia.createDatabaseIfNotExists();
            dbAgencia.create(newAgencia);
            dbUsers.createDatabaseIfNotExists();
            dbUsers.create(newUser);
            tf_createAgencyEmail.setText("");
            jp_createAgencyPassword.setText("");
            tf_createAgencyRTN.setText("");
            tf_createAgencyName.setText("");
            tf_createAgencyDirector.setText("");
            tf_createAgencyPhone.setText("");
            tf_createAgencyDescription.setText("");
            tf_createAgencyEmail.setText("");
        }
    }//GEN-LAST:event_jb_createAgencyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_createAgency;
    private javax.swing.JPasswordField jp_createAgencyPassword;
    private javax.swing.JTextArea tf_createAgencyAddress;
    private javax.swing.JTextArea tf_createAgencyDescription;
    private javax.swing.JTextField tf_createAgencyDirector;
    private javax.swing.JTextField tf_createAgencyEmail;
    private javax.swing.JTextField tf_createAgencyName;
    private javax.swing.JTextField tf_createAgencyPhone;
    private javax.swing.JTextField tf_createAgencyRTN;
    // End of variables declaration//GEN-END:variables
     
}
